#ifndef __GPIO_H__
#define __GPIO_H__

#define GPIOx_IN(GPIOx,PINx)    (u8)__GPIO_INPUT_PIN_GET(GPIOx, PINx)
#define GPIOx_OUT(GPIOx,PINx,y) {if(y){__GPIO_PIN_SET(GPIOx, PINx);}else{__GPIO_PIN_RESET(GPIOx, PINx);}}

#define CH1_CHECK1_IN GPIOx_IN(GPIOA,GPIO_PIN_6) 
#define CH1_CHECK2_IN GPIOx_IN(GPIOA,GPIO_PIN_7)

#define CH2_CHECK1_IN GPIOx_IN(GPIOC,GPIO_PIN_4)
#define CH2_CHECK2_IN GPIOx_IN(GPIOC,GPIO_PIN_5)

#define CH3_CHECK1_IN GPIOx_IN(GPIOB,GPIO_PIN_0)
#define CH3_CHECK2_IN GPIOx_IN(GPIOA,GPIO_PIN_5)

#define CH4_CHECK1_IN GPIOx_IN(GPIOA,GPIO_PIN_4)
#define CH4_CHECK2_IN GPIOx_IN(GPIOA,GPIO_PIN_3)

#define CH1_PROT_OUT(x) GPIOx_OUT(GPIOC,GPIO_PIN_0,x)
#define CH2_PROT_OUT(x) GPIOx_OUT(GPIOB,GPIO_PIN_4,x)
#define CH3_PROT_OUT(x) GPIOx_OUT(GPIOD,GPIO_PIN_2,x)
#define CH4_PROT_OUT(x) GPIOx_OUT(GPIOC,GPIO_PIN_2,x)


void Init_Gpio(void);



#endif
